name: Noels Sexy Fit
favicon: null
layout_spectrum: 0.49473
typography_spectrum: 1
title: 'Gotta Get It!!!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ee0b7e'
    - '#f685bd'
    - '#f23e99'
    - '#f35ba7'
  brandStrength: 0.9113647267222404
  lightness: 0.9139247161801904
  saturation: 0.046438912162557244
  rhythmicContrast: 0.75
purpose: []
