name: Noels Sexy Fit
favicon: null
layout_spectrum: 0.99539
typography_spectrum: 1
title: 'Gotta Get It!!!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9113647267222404
  lightness: 0.9139247161801904
  saturation: 0.046438912162557244
  rhythmicContrast: 0.75
purpose: []
