typography_spectrum: 1
color:
  brandColors:
    - '#ffffff'
    - '#ee0b7e'
    - '#f685bd'
    - '#f23e99'
    - '#f35ba7'
  brandStrength: 0.9113647267222404
  lightness: 0.9139247161801904
  saturation: 0.046438912162557244
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-83391720-1
  facebook: null
  twitter: null
name: Noels Sexy Fit
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Gotta Get It!!!
purpose: []
